import { RageShared } from "@shared/index";
import { Item } from "../inventory.types";

export const clothingItems: Item = {
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAT]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_HAT,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
        hash: "",
        key: "",
        quality: -1,
        image: "hat.svg",
        render: "hat.svg",
        name: "Hat",
        description: "Headgear.",
        count: 1,
        weight: 0.3,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],
        modelHash: "prop_proxy_hat_01",
        gender: null,
        isPlaced: false
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MASK]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_MASK,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "mask.svg",
        render: "mask.svg",
        name: "Mask",
        description: "Completely hides your face.",
        count: 1,
        weight: 0.3,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "p_orleans_mask_s"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
        hash: "",
        key: "",
        quality: -1,
        image: "glasses.svg",
        render: "glasses.svg",
        name: "Glasses",
        description: "",
        count: 1,
        weight: 0.1,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "prop_cs_sol_glasses"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
        hash: "",
        key: "",
        quality: -1,
        image: "earRings.svg",
        render: "earRings.svg",
        name: "Earrings",
        description: "",
        count: 1,
        weight: 0.05,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "p_tmom_earrings_s"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
        hash: "",
        key: "",
        quality: -1,
        image: "chain.svg",
        render: "chain.svg",
        name: "Chain",
        description: "Perfect accessory to flex.",
        count: 1,
        weight: 0.2,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "vw_prop_vw_backpack_01a"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "tShirt.svg",
        render: "tShirt.svg",
        name: "T-shirt",
        description: "",
        count: 1,
        weight: 0.3,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "prop_ld_tshirt_01"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TOP]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_TOP,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "top.svg",
        render: "top.svg",
        name: "Jacket",
        description: "",
        count: 1,
        weight: 2,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "prop_ld_shirt_01"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "armour.svg",
        render: "armour.svg",
        name: "Body armor",
        description: "Provides protection for the upper torso.",
        count: 1,
        weight: 10,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "prop_bodyarmour_03",
        amount: 100
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WATCH]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_WATCH,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
        hash: "",
        key: "",
        quality: -1,
        image: "watch.svg",
        render: "watch.svg",
        name: "Watch",
        description: "Wristwatch.",
        count: 1,
        weight: 0.1,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "vw_prop_vw_backpack_01a"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "gloves.svg",
        render: "gloves.svg",
        name: "Gloves",
        description: "",
        count: 1,
        weight: 0.1,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "vw_prop_vw_backpack_01a"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PANTS]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_PANTS,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "pants.svg",
        render: "pants.svg",
        name: "Pants",
        description: "",
        count: 1,
        weight: 1,
        maxStack: 1,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "bkr_prop_duffel_bag_01a"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOES]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_SHOES,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: -1,
        image: "shoes.svg",
        render: "shoes.svg",
        name: "Shoes",
        description: "",
        count: 1,
        weight: 2,
        maxStack: 10,
        options: ["putOn", "drop", "trade"],

        gender: null,
        isPlaced: false,
        modelHash: "v_res_fa_shoebox4"
    },
    [RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK]: {
        type: RageShared.Inventory.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK,
        typeCategory: RageShared.Inventory.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
        hash: "",
        key: "",
        quality: 0,
        image: "backpack.svg",
        render: "backpack.svg",
        name: "Backpack",
        description: "Increases inventory capacity.",
        count: 1,
        weight: 5,
        maxStack: 1,
        isPlaced: false,
        options: ["open", "putOn", "drop", "trade"],
        gender: null,
        modelHash: "vw_prop_vw_backpack_01a",
        items: {
            0: null,
            1: null,
            2: null,
            3: null,
            4: null,
            5: null,
            6: null,
            7: null,
            8: null,
            9: null,
            10: null,
            11: null,
            12: null,
            13: null,
            14: null,
            15: null,
            16: null,
            17: null,
            18: null,
            19: null,
            20: null,
            21: null,
            22: null,
            23: null
        }
    },
}