export namespace inventoryAssets {
    export const enum INVENTORY_CLOTHING {
        TYPE_HAT = 0,
        TYPE_MASK = 1,
        TYPE_GLASSES = 2,
        TYPE_EARRINGS = 3,
        TYPE_CHAIN = 4,
        TYPE_TSHIRT = 5,
        TYPE_JACKET = 6,
        TYPE_BACKPACK = 7,
        TYPE_WALLET = 8,
        TYPE_ARMOUR = 9,
        TYPE_WATCH = 10,
        TYPE_GLOVES = 11,
        TYPE_PANTS = 12,
        TYPE_SHOES = 13
    }
    export const INVENTORY_EQUIPMENTS: Record<string, string> = {
        hat: "0",
        mask: "1",
        glasses: "2",
        earRings: "3",
        chain: "4",
        tShirt: "5",
        top: "6",
        backpack: "7",
        wallet: "8",
        armour: "9",
        watch: "10",
        gloves: "11",
        pants: "12",
        shoes: "13"
    };
    export enum AMMO_TYPES {
        TYPE_PISTOL = "PISTOLAMMO",
        TYPE_50CAL = "REVOLVERAMMO",
        TYPE_SMG = "SMGAMMO",
        TYPE_GUAGE = "SHOTGUNAMMO",
        TYPE_RIFLE = "RIFLEAMMO",
        TYPE_SNIPER = "SNIPERAMMO",
        TYPE_LMG = "LMGAMMO"
    }
    export enum INVENTORY_CATEGORIES {
        CLOTHES = "clothes",
        POCKETS = "pockets"
    }

    export type Item = Record<string, RageShared.Interfaces.Inventory.IInventoryItem>;

    export const items: Item = {
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HAT]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HAT,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "hat.svg",
            render: "hat.svg",
            name: "Hat",
            description: "Headgear.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            modelHash: "prop_proxy_hat_01",
            gender: null,
            isPlaced: false
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MASK]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MASK,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "mask.svg",
            render: "mask.svg",
            name: "Mask",
            description: "Completely hides your face.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "p_orleans_mask_s"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GLASSES,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "glasses.svg",
            render: "glasses.svg",
            name: "Glasses",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_cs_sol_glasses"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_EARRINGS,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "earRings.svg",
            render: "earRings.svg",
            name: "Earrings",
            description: "",
            count: 1,
            weight: 0.05,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "p_tmom_earrings_s"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CHAIN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "chain.svg",
            render: "chain.svg",
            name: "Chain",
            description: "Perfect accessory to flex.",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TSHIRT,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "tShirt.svg",
            render: "tShirt.svg",
            name: "T-shirt",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_tshirt_01"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TOP]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TOP,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "top.svg",
            render: "top.svg",
            name: "Jacket",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_shirt_01"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ARMOUR,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "armour.svg",
            render: "armour.svg",
            name: "Body armor",
            description: "Provides protection for the upper torso.",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bodyarmour_03",
            amount: 100
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_WATCH]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_WATCH,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "watch.svg",
            render: "watch.svg",
            name: "Watch",
            description: "Wristwatch.",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GLOVES,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "gloves.svg",
            render: "gloves.svg",
            name: "Gloves",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PANTS]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PANTS,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "pants.svg",
            render: "pants.svg",
            name: "Pants",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "bkr_prop_duffel_bag_01a"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SHOES]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SHOES,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "shoes.svg",
            render: "shoes.svg",
            name: "Shoes",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 10,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "v_res_fa_shoebox4"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BACKPACK,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: 0,
            image: "backpack.svg",
            render: "backpack.svg",
            name: "Backpack",
            description: "Increases inventory capacity.",
            count: 1,
            weight: 5,
            maxStack: 1,
            isPlaced: false,
            options: ["putOn", "drop", "trade"],
            gender: null,
            modelHash: "vw_prop_vw_backpack_01a"
        },

        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DAGGER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DAGGER,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "dagger.svg",
            render: "dagger.svg",
            name: "dagger",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_dagger"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BAT]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BAT,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bat.svg",
            render: "bat.svg",
            name: "bat",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_bat"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BOTTLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BOTTLE,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bottle.svg",
            render: "bottle.svg",
            name: "bottle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_bottle"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CROWBAR]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CROWBAR,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "crowbar.svg",
            render: "crowbar.svg",
            name: "crowbar",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_crowbar"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flashlight.svg",
            render: "flashlight.svg",
            name: "flashlight",
            description: "",
            count: 1,
            weight: 0.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_FLASHLIGHT"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GOLFCLUB]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GOLFCLUB,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "golfclub.svg",
            render: "golfclub.svg",
            name: "golfclub",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_gclub"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HAMMER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HAMMER,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hammer.svg",
            render: "hammer.svg",
            name: "hammer",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_hammer"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HATCHET]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HATCHET,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hatchet.svg",
            render: "hatchet.svg",
            name: "hatchet",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_hatchet"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "knuckle.svg",
            render: "knuckle.svg",
            name: "knuckle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_KNUCKLE"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_KNIFE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_KNIFE,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "knife.svg",
            render: "knife.svg",
            name: "knife",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_knife_01"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MACHETE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MACHETE,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "machete.svg",
            render: "machete.svg",
            name: "machete",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_w_me_machette"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "switchblade.svg",
            render: "switchblade.svg",
            name: "switchblade",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_SWITCHBLADE"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "nightstick.svg",
            render: "nightstick.svg",
            name: "nightstick",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_nightstick"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_WRENCH]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_WRENCH,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "wrench.svg",
            render: "wrench.svg",
            name: "wrench",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_tool_wrench"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BATTLEAXE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BATTLEAXE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "battleaxe.svg",
            render: "battleaxe.svg",
            name: "battleaxe",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_fireaxe"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_POOLCUE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_POOLCUE,

            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "poolcue.svg",
            render: "poolcue.svg",
            name: "poolcue",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_pool_cue"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol.svg",
            render: "pistol.svg",
            name: "Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistolmk2.svg",
            render: "pistolmk2.svg",
            name: "MK2 Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpistol.svg",
            render: "combatpistol.svg",
            name: "Combat Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_combatpistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_APPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_APPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "appistol.svg",
            render: "appistol.svg",
            name: "Pistol AP",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_appistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "Stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL50]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PISTOL50,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol50.svg",
            render: "pistol50.svg",
            name: "Pistol 50",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol50",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistol.svg",
            render: "snspistol.svg",
            name: "SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistolmk2.svg",
            render: "snspistolmk2.svg",
            name: "MK2 SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavypistol.svg",
            render: "heavypistol.svg",
            name: "Heavy Pistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "vintagepistol.svg",
            render: "vintagepistol.svg",
            name: "Vintage Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_vintage_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLAREGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLAREGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flaregun.svg",
            render: "flaregun.svg",
            name: "Flaregun",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_flaregun",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanpistol.svg",
            render: "marksmanpistol.svg",
            name: "Marksman Pistol",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_marksmanpistol ",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "revolver.svg",
            render: "heavyrevolver.svg",
            name: "revolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "revolvermk2.svg",
            render: "revolvermk2.svg",
            name: "revolvermk2",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "doubleaction.svg",
            render: "doubleaction.svg",
            name: "doubleaction",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAYPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAYPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "raypistol.svg",
            render: "raypistol.svg",
            name: "raypistol",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "ceramicpistol.svg",
            render: "ceramicpistol.svg",
            name: "ceramicpistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "navyrevolver.svg",
            render: "navyrevolver.svg",
            name: "navyrevolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "gadgetpistol.svg",
            render: "gadgetpistol.svg",
            name: "gadgetpistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUNMP]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STUNGUNMP,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MICROSMG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MICROSMG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "microsmg.svg",
            render: "microsmg.svg",
            name: "microsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_microsmg",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smg.svg",
            render: "smg.svg",
            name: "smg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMG_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMG_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smgmk2.svg",
            render: "smgmk2.svg",
            name: "smgmk2",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultsmg.svg",
            render: "assaultsmg.svg",
            name: "assaultsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_assaultsmg",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPDW]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATPDW,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpdw.svg",
            render: "combatpdw.svg",
            name: "combatpdw",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_COMBATPDW",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "machinepistol.svg",
            render: "machinepistol.svg",
            name: "machinepistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MACHINEPISTOL",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MINISMG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MINISMG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "minismg.svg",
            render: "minismg.svg",
            name: "minismg",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MINISMG",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAYCARBINE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAYCARBINE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "raycarbine.svg",
            render: "raycarbine.svg",
            name: "raycarbine",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "SMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgun.svg",
            render: "pumpshotgun.svg",
            name: "pumpshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgunmk2.svg",
            render: "pumpshotgunmk2.svg",
            name: "pumpshotgunmk2",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "sawnoffshotgun.svg",
            render: "sawnoffshotgun.svg",
            name: "sawnoffshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_sawnoff",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultshotgun.svg",
            render: "assaultshotgun.svg",
            name: "assaultshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupshotgun.svg",
            render: "bullpupshotgun.svg",
            name: "bullpupshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_bullpupshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MUKSET]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MUKSET,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "musket.svg",
            render: "musket.svg",
            name: "musket",
            description: "",
            count: 1,
            weight: 4.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_musket",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyshotgun.svg",
            render: "heavyshotgun.svg",
            name: "heavyshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_heavyshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "dbshotgun.svg",
            render: "dbshotgun.svg",
            name: "dbshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "autoshotgun.svg",
            render: "autoshotgun.svg",
            name: "autoshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatshotgun.svg",
            render: "combatshotgun.svg",
            name: "combatshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultrifle.svg",
            render: "assaultrifle.svg",
            name: "assaultrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultriflemk2.svg",
            render: "assaultriflemk2.svg",
            name: "assaultriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "carbinerifle.svg",
            render: "carbinerifle.svg",
            name: "carbinerifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "carbineriflemk2.svg",
            render: "carbineriflemk2.svg",
            name: "carbineriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "advancedrifle.svg",
            render: "advancedrifle.svg",
            name: "advancedrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_advancedrifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbine.svg",
            render: "specialcarbine.svg",
            name: "specialcarbine",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbinemk2.svg",
            render: "specialcarbinemk2.svg",
            name: "specialcarbinemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpuprifle.svg",
            render: "bullpuprifle.svg",
            name: "bullpuprifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupriflemk2.svg",
            render: "bullpupriflemk2.svg",
            name: "bullpupriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "compactrifle.svg",
            render: "compactrifle.svg",
            name: "compactrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "militaryrifle.svg",
            render: "militaryrifle.svg",
            name: "militaryrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyrifle.svg",
            render: "heavyrifle.svg",
            name: "heavyrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "tacticalrifle.svg",
            render: "tacticalrifle.svg",
            name: "tacticalrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "mg.svg",
            render: "mg.svg",
            name: "mg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_mg",
            ammoType: "LMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmg.svg",
            render: "combatmg.svg",
            name: "combatmg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmgmk2.svg",
            render: "combatmgmk2.svg",
            name: "combatmgmk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GUSENBERG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GUSENBERG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "gusenberg.svg",
            render: "gusenberg.svg",
            name: "gusenberg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_gusenberg",
            ammoType: "LMGAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "sniperrifle.svg",
            render: "sniperrifle.svg",
            name: "sniperrifle",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_sniperrifle",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysniper.svg",
            render: "heavysniper.svg",
            name: "heavysniper",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysnipermk2.svg",
            render: "heavysnipermk2.svg",
            name: "heavysnipermk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanrifle.svg",
            render: "marksmanrifle.svg",
            name: "marksmanrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanriflemk2.svg",
            render: "marksmanriflemk2.svg",
            name: "marksmanriflemk2",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "precisionrifle.svg",
            render: "precisionrifle.svg",
            name: "precisionrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "compactlauncher.svg",
            render: "compactlauncher.svg",
            name: "compactlauncher",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FIREWORK]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FIREWORK,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "firework.svg",
            render: "firework.svg",
            name: "firework",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_firework",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "granadelaunchersmoke.svg",
            render: "granadelaunchersmoke.svg",
            name: "granadelaunchersmoke",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "grenadelauncher.svg",
            render: "grenadelauncher.svg",
            name: "grenadelauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hominglauncher.svg",
            render: "hominglauncher.svg",
            name: "hominglauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_homing",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MINIGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MINIGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "minigun.svg",
            render: "minigun.svg",
            name: "minigun",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_minigun",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAILGUN]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RAILGUN,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "railgun.svg",
            render: "railgun.svg",
            name: "railgun",
            description: "",
            count: 1,
            weight: 6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_railgun",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RPG]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_RPG,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "rpg.svg",
            render: "rpg.svg",
            name: "rpg",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_rpg",
            ammoType: ""
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BALL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BALL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "ball.svg",
            render: "ball.svg",
            name: "ball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_golf_ball"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BZGAS]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_BZGAS,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bzgas.svg",
            render: "bzgas.svg",
            name: "bzgas",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smokegrenade.svg",
            render: "smokegrenade.svg",
            name: "smokegrenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLARE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_FLARE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flare.svg",
            render: "flare.svg",
            name: "flare",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_am_flare"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_GRENADE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "grenade.svg",
            render: "grenade.svg",
            name: "grenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_grenadefrag"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MOLOTOV]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_MOLOTOV,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "molotov.svg",
            render: "molotov.svg",
            name: "molotov",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_molotov"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "proximymine.svg",
            render: "proximymine.svg",
            name: "proximymine",
            description: "",
            count: 1,
            weight: 12,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_apmine"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PIPEBOMB]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_PIPEBOMB,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pipebomb.svg",
            render: "pipebomb.svg",
            name: "pipebomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNOWBALL]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_SNOWBALL,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snowball.svg",
            render: "snowball.svg",
            name: "snowball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_snowball"
        },
        [RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STICKYBOMB]: {
            type: RageShared.Enums.ITEM_TYPES.ITEM_TYPE_STICKYBOMB,
            typeCategory: RageShared.Enums.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stickybomb.svg",
            render: "stickybomb.svg",
            name: "stickybomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        }
    };
}
